### ISSUE TITLE
spatial community analysis

### ISSUE THREAD

**Issue by ahorlova** [BodenmillerGroup/ImagingWorkshop2023#2]
Hi!. I have a question related to spatial community analysis where you see spatial context clusters (e. g. 1_6, 1_2_3_5 etc.). Am I correct: they are intermediate zones between neighbourhoods. Are there other interpretation for these zones, except for transitional areas between functional clusters?

**Comment by jwindhager** [comment]
Hi @ahorlova! Since you've closed this issue, we assume this has been addressed already. Please re-open if that's not the case. Cheers

**Comment by nilseling** [comment]
Yes, this was answered live ;)
