### ISSUE TITLE
Error in add addtional metadata 

### ISSUE THREAD

**Issue by Joyee77** [BodenmillerGroup/ImagingWorkshop2023#5]
Hi I am having error at the add additional metadata step (session3 line 194-204), which is below:
```{r add-indication}
library(openxlsx)
library(stringr)
meta <- read.xlsx("/Users/Joyee/Documents/IMC-final/steinbock-new/sample_metadata.xlsx")

spe$patient_id <- as.vector(str_extract_all(spe$sample_id, "20230514 V", simplify = TRUE))
spe$ROI <- as.vector(str_extract_all(spe$sample_id, "[a-zA-Z]+", simplify = TRUE))
spe$indication <- meta$Indication[match(spe$patient_id, meta$sample.id)]

unique(spe$indication)
```
The sample name of my files are quite different from the example data. Rather than patient[1-4], mine is year-month-date+my first name+donor number+disease condition. Therefore, the string length of id is different and the pattern is different. May I ask what would be a suitable way to modify the code? Or it is better I uniform the naming as the example data. For example: healthy[1-6], diseased [1-6]?

May thanks,
Joyee

**Comment by nilseling** [comment]
Hi @Joyee77,

This repository is not maintained. In addition, we don't have the capacity to provide basic R coding advise. For this I would recommend to attend some courses or find help on your side.
